<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title><?=$this->e($title)?> - zend-expressive</title>
    <link rel="shortcut icon" href="https://framework.zend.com/ico/favicon.ico" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" />
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet" />
    <style>
        body { padding-top: 70px; }
        .app { min-height: 100vh; }
        .app-footer { padding-bottom: 1em; }
        .zf-green, h2 a { color: #68b604; }
    </style>
    <?=$this->section('stylesheets')?>
</head>
<body class="app">
    <header class="app-header">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Brand -->
                    <a class="navbar-brand" href="/">
                        <i class="fa fa-home"></i> Home
                    </a>
                </div>
                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a href="<?= $this->url('post.list') ?>" class="nav-link">
                                <i class="fa fa-thumbtack"></i> Posts
                            </a>
                        </li>
                        <?php if ($authorized): ?>
                        <li class="nav-item">
                            <a href="<?= $this->url('post.create') ?>" class="nav-link">
                                <i class="fa fa-plus"></i> Add New
                            </a>
                        </li>
                        <?php endif; ?>
                        <li class="nav-item">
                            <a href="<?= $this->url('hello', [], ['target'=>'Me']) ?>" class="nav-link">
                                <i class="fa fa-hand-paper"></i> Hello
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="/api/ping" class="nav-link">
                                Ping Test
                            </a>
                        </li>
                        <?php if ($authorized): ?>
                        <li class="nav-item">
                            <a href="/logout" class="nav-link">
                                Logout
                            </a>
                        </li>
                        <?php else: ?>
                        <li class="nav-item">
                            <a href="/login" class="nav-link">
                                Login
                            </a>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">
            <?=$this->section('content')?>
        </main>
    </div>

    <footer class="app-footer">
        <div class="container">
            <hr />
            <?php if ($this->section('footer')): ?>
                <?=$this->section('footer')?>
            <?php endif ?>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <?=$this->section('javascript')?>
</body>
</html>
