version: '3'

services:
  go:
    build: .docker/go
    volumes:
      - ./server:/go/src/server
    working_dir: /go/src/server
    command: ["version"]

  php:
    build: .docker/php
    depends_on:
      - database
    volumes:
      - ./application:/var/www/blog
    command: ["--version"]

  composer:
    build: .docker/composer
    volumes:
      - ./application:/app
    command: ["--version"]

  application:
    build: .docker/application
    volumes:
      - ./application:/var/www/blog
      - ./server/server:/var/www/blog/rr
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: blog
    security_opt:
      - seccomp:unconfined