version: '3'

services:
  go:
    image: "golang:1.13"
    volumes:
      - ./server:/go/src/server
    working_dir: /go/src/server

  composer:
    image: "composer:latest"
    volumes:
      - ./application:/app

  php:
    build: .docker/php
    volumes:
      - ./application:/var/www/blog
      - ./server/server:/var/www/blog/rr
    ports:
      - 8080:8080
    command: "/var/www/blog/rr serve -d -v"
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: blog