version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - 8080:80
    volumes:
      - .:/var/www/blog
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    build: .docker/php
    volumes:
      - .:/var/www/blog
    depends_on:
      - db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: blog