<?php
/**
 * This file generated by Zend\Expressive\Tooling\Factory\ConfigInjector.
 *
 * Modifications should be kept at a minimum, and restricted to adding or
 * removing factory definitions; other dependency types may be overwritten
 * when regenerating this file via zend-expressive-tooling commands.
 */
 
declare(strict_types=1);

return [
    'dependencies' => [
        'factories' => [
            App\Handler\HelloHandler::class => App\Handler\HelloHandlerFactory::class,
            Post\Handler\PostCreateHandler::class => Post\Factory\PostCreateHandlerFactory::class,
            Post\Handler\PostDeleteHandler::class => Post\Factory\PostDeleteHandlerFactory::class,
            Post\Handler\PostDetailHandler::class => Post\Factory\PostDetailHandlerFactory::class,
            Post\Handler\PostListHandler::class => Post\Factory\PostListHandlerFactory::class,
            Post\Handler\PostUpdateHandler::class => Post\Factory\PostUpdateHandlerFactory::class,
        ],
    ],
];
